apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
   app: automated 
spec:
  replicas: 2
  selector:
   matchLabels:
      app: automated
  template:
    metadata:
      labels:
        app: automated
    spec:
      containers:
      - name: hello-world
        image: krvnb/my-docker-image:latest
        resources:
          limits:
            memory: "1000Mi"
            cpu: "700m"
        ports:
        - containerPort: 9090


---

apiVersion: v1
kind: Service
metadata:
  name: my-svc
spec:
  type: NodePort
  selector:
    app: automated
  ports:
  - port: 9091
    targetPort: 9090
    nodePort: 30008

